import React from "react";
import GoogleAds from "../components/GoogleAds";

const featureModels = [
  { id: 1, img: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 2, img: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80", likes: 99 },
  { id: 3, img: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80", likes: 20 },
  { id: 4, img: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=600&q=80", likes: 50 },
];

const aiImages = [
  { id: 1, img: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 2, img: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 3, img: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 4, img: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 5, img: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 6, img: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 7, img: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80", likes: 10 },
  { id: 8, img: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80", likes: 10 },
];

export default function Home() {
  return (
    <div className="flex-1 flex flex-col p-8">
      <GoogleAds adSlot="1831284933" />
      <h1 className="text-white text-3xl font-bold mb-6">Home Page</h1>
      {/* Feature Model Carousel */}
      <div className="mb-10">
        <h2 className="text-yellow-400 text-2xl font-bold mb-2 flex items-center">✨ Feature Model</h2>
        <div className="flex items-center gap-4 overflow-x-auto pb-2">
          <button className="text-yellow-400 text-2xl px-2">&#8592;</button>
          {featureModels.map((item) => (
            <div key={item.id} className="relative min-w-[250px] max-w-xs rounded-xl overflow-hidden shadow-lg border border-gray-700 bg-black/80">
              <img src={item.img} alt="feature" className="w-full h-40 object-cover" />
              <div className="absolute top-2 right-2 bg-black/70 rounded-full px-3 py-1 flex items-center text-white text-sm font-semibold">
                <span className="mr-1">🤍</span> {item.likes}
              </div>
            </div>
          ))}
          <button className="text-yellow-400 text-2xl px-2">&#8594;</button>
        </div>
      </div>
      {/* AI Image Masonry Grid */}
      <div className="mb-6">
        <h2 className="text-yellow-400 text-2xl font-bold mb-1 flex items-center">🔥 Created with the AI Image Generator</h2>
        <p className="text-gray-300 mb-4">Get inspired by the images generated by our text-to-image AI. Click on them to use the prompts.</p>
        <div className="columns-1 sm:columns-2 md:columns-3 lg:columns-4 gap-6 space-y-6">
          {aiImages.map((img) => (
            <div key={img.id} className="mb-6 break-inside-avoid rounded-xl overflow-hidden shadow-lg border border-gray-700 bg-black/80 relative">
              <img src={img.img} alt="AI" className="w-full object-cover rounded-xl" />
              <div className="absolute top-2 right-2 bg-black/70 rounded-full px-3 py-1 flex items-center text-white text-sm font-semibold">
                <span className="mr-1">🤍</span> {img.likes}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
} 
